bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost dbname=restful_api_dev sslmode=disable user=user password=userpassword"
token_secret = "dasjd2184812u*AW*$UWau)(_!(@JFjaskdauD@*Jd9aJDjsk"